# Generated by Django 6.0.6 on 2026-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exipire_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OTP code',
                'verbose_name_plural': 'OTP code',
            },
        ),
    ]
